kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: dati-semantic-webvowl
  namespace: ndc-test
  labels:
    application: dati-semantic-webvowl
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: dati-semantic-webvowl
  template:
    metadata:
      name: dati-semantic-webvowl
      creationTimestamp: null
      labels:
        application: dati-semantic-webvowl
        deploymentConfig: dati-semantic-webvowl
    spec:
      containers:
        - resources:
            limits:
              cpu: 800m
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 512Mi
          # readinessProbe:  # FIXME
          #   httpGet:
          #     path: /onto/CPV
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 8
          #   successThreshold: 1
          #   failureThreshold: 300
          # livenessProbe: # FIXME
          #   httpGet:
          #     path: /onto/CPV
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 8
          #   successThreshold: 1
          #   failureThreshold: 300
          terminationMessagePath: /dev/termination-log
          name: dati-semantic-webvowl
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            ghcr.io/teamdigitale/dati-semantic-webvowl:20221124-8-f196be9
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
