kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: dati-semantic-lode
  namespace: ndc-dev
  labels:
    application: dati-semantic-lode
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: dati-semantic-lode
  template:
    metadata:
      name: dati-semantic-lode
      creationTimestamp: null
      labels:
        application: dati-semantic-lode
        deploymentConfig: dati-semantic-lode
    spec:
      containers:
        - resources:
            limits:
              cpu: 800m
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 512Mi
          # readinessProbe:  # FIXME
          #   httpGet:
          #     path: /onto/CPV
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 8
          #   successThreshold: 1
          #   failureThreshold: 300
          # livenessProbe: # FIXME
          #   httpGet:
          #     path: /onto/CPV
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 8
          #   successThreshold: 1
          #   failureThreshold: 300
          terminationMessagePath: /dev/termination-log
          name: dati-semantic-lode
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            ghcr.io/teamdigitale/LODE:20221122-10-66ceb88
          env:
            - name: EXTERNAL_URL
              value: "https://lode-ndc-dev.apps.cloudpub.testedev.istat.it/lode"
              # - name: MATOMO_SITE_ID  # FIXME
              #   value: "35"
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
