kind: Service
apiVersion: v1
metadata:
  name: dati-semantic-lode
  namespace: ndc-test
  labels:
    application: dati-semantic-lode
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentConfig: dati-semantic-lode
  sessionAffinity: None
