kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: dati-semantic-frontend
  namespace: ndc-test
  labels:
    application: dati-semantic-frontend
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: dati-semantic-frontend
  template:
    metadata:
      name: dati-semantic-frontend
      creationTimestamp: null
      labels:
        application: dati-semantic-frontend
        deploymentConfig: dati-semantic-frontend
    spec:
      containers:
        - resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 8
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 8
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: dati-semantic-frontend
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            ghcr.io/teamdigitale/dati-semantic-frontend:20240911-1226-5ca2117
          env:
            - name: API_URL
              value: /api
            - name: SPARQL_ENDPOINT_URL
              value: https://virtuoso-test-external-service-ndc-test.apps.cloudpub.testedev.istat.it/sparql/
            - name: MATOMO_SITE_ID
              value: "34"
            - name: NDC_MAINTENANCE_MESSAGE
              value: Il giorno 24 settembre 2024, dalle 9 alle 15, i servizi del catalogo potrebbero presentare rallentamenti o malfunzionamenti temporanei per gli interventi tecnici in corso. Ci scusiamo per il disagio.
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
