kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: dati-semantic-backend
  namespace: ndc-test
  labels:
    application: dati-semantic-backend
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: { }
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: dati-semantic-backend
  template:
    metadata:
      name: dati-semantic-backend
      creationTimestamp: null
      labels:
        application: dati-semantic-backend
        deploymentConfig: dati-semantic-backend
    spec:
      containers:
        - resources:
            limits:
              cpu: 800m
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /status/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /status/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: dati-semantic-backend
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            ghcr.io/teamdigitale/dati-semantic-backend:20211207-160-e87b479
          env:
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: http://temporary-elasticsearch:9200
            - name: VIRTUOSO_SPARQL_URL
              value: http://temporary-virtuoso:8890/sparql
            - name: VIRTUOSO_SPARQL_GRAPH_STORE_URL
              value: http://temporary-virtuoso:8890/sparql-graph-crud
            - name: HARVESTER_REPOSITORIES
              value: "https://github.com/ash1425/sample-ontology-repo"
            - name: NDC_BASE_URL
              value: https://ndc-test.apps.cloudpub.testedev.istat.it/api
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://temporary-mysql:3306
            - name: SPRING_DATASOURCE_USERNAME
              value: ndc_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: ndc_password
            - name: TO_TRIGGER_DEPLOPYMENT
              value: "8-dec-2021"
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
