kind: Service
apiVersion: v1
metadata:
  name: dati-semantic-backend
  namespace: ndc-dev
  labels:
    application: dati-semantic-backend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deployment: dati-semantic-backend
  sessionAffinity: None
